# T3.1 - Human Approval - Approved
# 
# Purpose: Validate human approval flow when approval is granted
# Agent: process-echo, process-worker
# Expected: Process pauses at approval, continues when approved
#
# Test Validates:
# - human_approval step type works
# - Execution pauses at approval step
# - Approval API works to submit decision
# - Process continues after approval
# - Approval metadata available to downstream steps

name: t3.1-approval-approved
version: "1.0.0"
description: "Human approval test - validates approved flow"

triggers:
  - type: manual
    id: manual-start

steps:
  - id: draft
    name: Create Draft
    type: agent_task
    agent: process-worker
    message: "Create a draft document for review"
    timeout: 60s

  - id: review-approval
    name: Review Approval
    type: human_approval
    depends_on:
      - draft
    title: "Draft Review Required"
    description: |
      Please review the draft and approve or reject.
      
      Draft content: {{steps.draft.output.output.result}}
    timeout: 1h
    approvers:
      - "test@example.com"

  - id: publish
    name: Publish
    type: agent_task
    agent: process-echo
    depends_on:
      - review-approval
    condition: "{{steps.review-approval.decision}} == 'approved'"
    message: |
      Publishing approved draft.
      Approved by: {{steps.review-approval.decided_by}}
      Comment: {{steps.review-approval.comment}}
    timeout: 30s

# Test Procedure:
# 1. Start execution - should pause at review-approval
# 2. Check execution status: should be PAUSED or RUNNING with step WAITING_APPROVAL
# 3. Submit approval via API:
#    POST /api/executions/{id}/steps/review-approval/approve
#    { "decision": "approved", "comment": "Looks good!" }
# 4. Execution should continue to publish step
# 5. Process completes

# Verification Checklist:
# [ ] draft step completes with content
# [ ] Execution pauses at review-approval
# [ ] Approval can be submitted via API
# [ ] publish step receives approval metadata
# [ ] Process completes with status COMPLETED
# [ ] Approval decision and comment are accessible
