# T3.3 - Human Approval with Timeout
# 
# Purpose: Validate approval timeout behavior
# Agent: process-echo
# Expected: When approval times out, configured action is taken
#
# Test Validates:
# - Short timeout triggers timeout behavior
# - Timeout action (fail, auto_approve, auto_reject) works
# - Timeout event is recorded

name: t3.3-approval-timeout
version: "1.0.0"
description: "Human approval timeout test - validates timeout handling"

triggers:
  - type: manual
    id: manual-start

steps:
  - id: prepare
    name: Prepare Content
    type: agent_task
    agent: process-echo
    message: "Preparing content for approval"
    timeout: 30s

  - id: short-approval
    name: Short Approval Window
    type: human_approval
    depends_on:
      - prepare
    title: "Quick Approval (30 second timeout)"
    description: |
      This approval has a 30-second timeout for testing.
      DO NOT approve/reject - let it timeout.
    timeout: 30s
    on_timeout: fail
    approvers:
      - "test@example.com"

  - id: post-approval
    name: Post Approval
    type: agent_task
    agent: process-echo
    depends_on:
      - short-approval
    message: "This should not run if timeout fails the process"
    timeout: 30s

# Test Procedure:
# 1. Start execution
# 2. DO NOT submit any approval
# 3. Wait 30+ seconds
# 4. Check execution status - should be FAILED due to timeout

# Timeout Actions:
# - on_timeout: fail - Process fails (test this)
# - on_timeout: auto_approve - Auto-approves (test separately)
# - on_timeout: auto_reject - Auto-rejects (test separately)

# Verification Checklist:
# [ ] Approval step starts and waits
# [ ] After 30 seconds, timeout triggers
# [ ] With on_timeout: fail, execution status becomes FAILED
# [ ] post-approval does NOT run
# [ ] Timeout is recorded in step details
