# T3.4 - Human Approval with Artifacts
# 
# Purpose: Validate approval with file artifacts for review
# Agent: process-worker, process-echo
# Expected: Approver can see referenced files/outputs
#
# Test Validates:
# - Artifacts can be referenced in approval
# - File paths from previous steps are accessible
# - Approval description can include complex data

name: t3.4-approval-artifacts
version: "1.0.0"
description: "Human approval with artifacts test - validates file references"

triggers:
  - type: manual
    id: manual-start

steps:
  - id: generate-report
    name: Generate Report
    type: agent_task
    agent: process-worker
    message: "Generate a detailed report with findings"
    timeout: 90s

  - id: generate-summary
    name: Generate Summary
    type: agent_task
    agent: process-echo
    depends_on:
      - generate-report
    message: |
      Create summary of report:
      Quality score: {{steps.generate-report.output.output.details.quality_score}}
      Confidence: {{steps.generate-report.output.output.details.confidence}}
    timeout: 30s

  - id: review-with-artifacts
    name: Review with Artifacts
    type: human_approval
    depends_on:
      - generate-report
      - generate-summary
    title: "Report Review with Artifacts"
    description: |
      Please review the following materials:
      
      ## Full Report
      {{steps.generate-report.output.output.result}}
      
      ## Summary
      {{steps.generate-summary.output.data.echo}}
      
      ## Quality Metrics
      - Score: {{steps.generate-report.output.output.details.quality_score}}
      - Confidence: {{steps.generate-report.output.output.details.confidence}}
      - Items Processed: {{steps.generate-report.output.output.details.items_processed}}
    timeout: 1h
    approvers:
      - "reviewer@example.com"
    artifacts:
      - path: "{{steps.generate-report.output.files_created}}"
        description: "Generated report files"

  - id: finalize
    name: Finalize
    type: agent_task
    agent: process-echo
    depends_on:
      - review-with-artifacts
    message: "Report finalized with approval"
    timeout: 30s

# Verification Checklist:
# [ ] generate-report produces output with files_created
# [ ] Approval description shows interpolated values
# [ ] Artifacts section references file paths
# [ ] Approver sees complete context
# [ ] Approval submission works
# [ ] Process completes
