# T1.4 - Step with Structured Output
# 
# Purpose: Validate nested JSON output and deep path references
# Agent: process-echo (with /structured command), process-worker
# Expected: Nested paths like {{steps.X.output.level1.level2.level3.value}} work
#
# Test Validates:
# - Agents can return complex nested JSON
# - Expression evaluator handles deep paths
# - Nested object references work in templates
# - Array access in templates (if supported)

name: t1.4-structured-output
version: "1.0.0"
description: "Structured output test - validates nested JSON and deep path references"

triggers:
  - type: manual
    id: manual-start

steps:
  - id: generate-structure
    name: Generate Nested Structure
    type: agent_task
    agent: process-echo
    message: "/structured"
    timeout: 30s

  - id: use-nested-value
    name: Use Nested Value
    type: agent_task
    agent: process-echo
    depends_on:
      - generate-structure
    message: "Deep value: {{steps.generate-structure.output.level1.level2.level3.value}}"
    timeout: 30s

  - id: worker-analysis
    name: Worker Analysis
    type: agent_task
    agent: process-worker
    depends_on:
      - generate-structure
    message: "Analyze this structure: {{steps.generate-structure.output}}"
    timeout: 60s

  - id: combine-results
    name: Combine Results
    type: agent_task
    agent: process-echo
    depends_on:
      - use-nested-value
      - worker-analysis
    message: |
      Combined results:
      - Nested value result: {{steps.use-nested-value.output.data.echo}}
      - Worker quality score: {{steps.worker-analysis.output.output.details.quality_score}}
    timeout: 30s

# Expected Output from generate-structure:
# {
#   "level1": {
#     "level2": {
#       "level3": {
#         "value": "deep-value",
#         "array": [1, 2, 3]
#       }
#     }
#   }
# }

# Verification Checklist:
# [ ] generate-structure returns nested JSON
# [ ] use-nested-value receives "deep-value" in its message
# [ ] worker-analysis receives full structure
# [ ] combine-results can reference paths from multiple upstream steps
# [ ] No template substitution errors
# [ ] All steps complete successfully
