# T5.4 - Concurrent Executions
# 
# Purpose: Test execution concurrency limits
# Agent: process-echo
# Expected: Multiple executions run, limits enforced
#
# Test Validates:
# - Multiple instances of same process can run
# - Global limit (50) is not exceeded
# - Per-process limit (3) is enforced
# - 429 returned when limit exceeded

name: t5.4-concurrent-executions
version: "1.0.0"
description: "Concurrent executions test - validates execution limits"

triggers:
  - type: manual
    id: manual-start

# Default limits from IT5:
# - max_concurrent_executions: 50 (global)
# - default_max_instances: 3 (per-process)

config:
  max_concurrent_instances: 3  # Allow max 3 of this process running

steps:
  - id: start
    name: Start
    type: agent_task
    agent: process-echo
    message: "Concurrent test started"
    timeout: 30s

  - id: slow-work
    name: Slow Work
    type: agent_task
    agent: process-failer
    depends_on: [start]
    message: "/timeout 30"  # Takes 30 seconds
    timeout: 60s

  - id: finish
    name: Finish
    type: agent_task
    agent: process-echo
    depends_on: [slow-work]
    message: "Concurrent test completed"
    timeout: 30s

# Test Procedure:
# 1. Start execution #1
# 2. Immediately start execution #2
# 3. Immediately start execution #3
# 4. Try to start execution #4 - should get 429 (limit exceeded)
# 5. Wait for one to complete
# 6. Try execution #4 again - should succeed

# API Calls:
# POST /api/processes/{id}/execute - start each
# GET /api/executions/limits/status - check current limits

# Verification Checklist:
# [ ] Execution #1 starts
# [ ] Execution #2 starts (concurrent)
# [ ] Execution #3 starts (concurrent)
# [ ] Execution #4 returns 429 Too Many Requests
# [ ] After one completes, execution #4 can start
# [ ] All complete eventually
# [ ] GET /api/executions/limits/status shows correct counts
