# T4.1 - Agent Returns Error
# 
# Purpose: Validate error propagation when agent fails
# Agent: process-failer
# Expected: Step fails, execution fails, error captured in details
#
# Test Validates:
# - Agent errors are captured
# - Step status becomes FAILED
# - Execution status becomes FAILED (default behavior)
# - Error message is accessible

name: t4.1-agent-error
version: "1.0.0"
description: "Agent error test - validates error propagation"

triggers:
  - type: manual
    id: manual-start

steps:
  - id: setup
    name: Setup
    type: agent_task
    agent: process-echo
    message: "Setting up test"
    timeout: 30s

  - id: fail-step
    name: Failing Step
    type: agent_task
    agent: process-failer
    depends_on:
      - setup
    message: "/fail"
    timeout: 30s

  - id: after-fail
    name: After Fail (should not run)
    type: agent_task
    agent: process-echo
    depends_on:
      - fail-step
    message: "This should not execute"
    timeout: 30s

# Expected Flow:
# 1. setup completes
# 2. fail-step fails (agent returns error)
# 3. after-fail never executes
# 4. Execution status: FAILED

# Verification Checklist:
# [ ] setup completes successfully
# [ ] fail-step receives /fail command
# [ ] fail-step status becomes FAILED
# [ ] Error message captured: "Simulated agent failure"
# [ ] after-fail status is PENDING (never started)
# [ ] Execution status is FAILED
# [ ] Error details accessible via API
